request for tack 4
reuven12/MailStone4 pull request #1
Opened 2021-08-24 12:40 UTC by reuven12

2021-08-25 06:25 UTC, Shahar-Y requested changes
I see too many eslint rules have been disabled. Do not disable rules unless consulted with me.
Job well done, but it needs some fixes. separate the controller and the repository, remove the rules from the files and put them all in the `eslintrc` file, and only if I approved them.
After you make the changes - tell me to recheck.
Also, don't resolve the comments I wrote so I can see them when I re-check.

2021-08-25 06:25 UTC, Shahar-Y commented on package.json
> +    "url": "git+https://github.com/reuven12/Mileston4.git"
It seems the configuration here was not done "naturally": was the package.json copied and then changed manually? 
The URL should have been more like `https://github.com/reuven12/MailStone4.git`. 
Make sure that in new projects you use `npm init` after cloning the empty github repo, and then the only parts in pachage.json allowed to paste inside are the scripts (also must be done carefully)

2021-08-25 06:25 UTC, Shahar-Y commented on src/app.ts
> +/* eslint-disable import/no-extraneous-dependencies */
Disabling eslint rules is done in a single file(probably eslintrc. remove it from here), otherwise you will have to put it in every file.

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +/* eslint-disable camelcase */
Same here and in all of the files. remove the rules from here.

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +/* eslint-disable import/no-unresolved */
This should not be disabled.

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +/* eslint-disable import/no-extraneous-dependencies */
This should not be disabled.

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +/* eslint-disable prefer-const */
This should not be disabled.

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +/* eslint-disable prefer-destructuring */
This should not be disabled.

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +  const chck: any = req.body.line_number;
Don't use `any`

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +      const newBus = await bus.save();
use the interface to specify the type

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +};
This contains both the controller and the repository. the controller should not "talk" to the mongoose directly. 
Sseperate to anothe `repository` file.

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +  const numberStation2: number = parseInt(req.query.numberStation2 as string);
This part is the controller

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +    ]);
This part belongs to the repository

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +    const getDistans = await BusesModel.aggregate([
```suggestion
    const getDistance = await BusesModel.aggregate([
```

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/bus.controller.ts
> +    const numbers2: number[] = Object.values(Station2);
`numpers1,2` is not informative. rename it

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/stations.contrroller.ts
> +/* eslint-disable import/no-extraneous-dependencies */
remove rules

2021-08-25 06:25 UTC, Shahar-Y commented on src/controllers/stations.contrroller.ts
> +  });
same here. seperate the controller and the repository

2021-08-25 06:25 UTC, Shahar-Y commented on src/interface/bus.interface.ts
> +  bus_color: String;
```suggestion
  lineNumber: Number;
  busColor: String;
```

2021-08-25 06:25 UTC, Shahar-Y commented on src/interface/bus.interface.ts
> +  getDistans: Number | String;
```suggestion
  getDistance: Number | String;
```

2021-08-25 06:25 UTC, Shahar-Y commented on src/interface/station.interface.ts
> +  numberStation: Number;
```suggestion
  stationNumber: Number;
```

2021-08-25 06:25 UTC, Shahar-Y commented on src/models/bus.model.ts
> +    line_number: {
```suggestion
    lineNumber: {
```

2021-08-25 06:25 UTC, Shahar-Y commented on src/models/bus.model.ts
> +    bus_color: {
```suggestion
    busColor: {
```

2021-08-25 06:25 UTC, Shahar-Y commented on src/models/station.model.ts
> +/* eslint-disable import/prefer-default-export */
remove rules

2021-08-25 06:25 UTC, Shahar-Y commented on src/models/station.model.ts
> +  station_Name: {
```suggestion
  stationName: {
```

2021-08-25 06:25 UTC, Shahar-Y commented on src/models/station.model.ts
> +  number_station: {
```suggestion
  stationNumber: {
```

2021-08-25 06:25 UTC, Shahar-Y commented on src/routes/bus.router.ts
> +router.get('/getDistans/', busController.getTime);
so is it `getDistance` or `getTime`?

2021-08-25 06:25 UTC, Shahar-Y commented on src/routes/bus.router.ts
> +router.get('/getDistans/', busController.getTime);
```suggestion
router.get('/getDistance/', busController.getTime);
```

2021-08-25 06:25 UTC, Shahar-Y commented on src/routes/stations.router.ts
> +/* eslint-disable import/no-extraneous-dependencies */
remove rules

2021-08-31 08:51 UTC, reuven12 commented on src/controllers/bus.controller.ts
> +/* eslint-disable import/no-extraneous-dependencies */
done

2021-08-31 08:51 UTC, reuven12 commented on src/models/station.model.ts
> +/* eslint-disable import/prefer-default-export */
done

2021-08-31 08:52 UTC, reuven12 commented on src/models/station.model.ts
> +  station_Name: {
done

2021-08-31 08:52 UTC, reuven12 commented on src/models/station.model.ts
> +  number_station: {
done

2021-08-31 08:52 UTC, reuven12 commented on src/routes/bus.router.ts
> +router.get('/getDistans/', busController.getTime);
done

2021-08-31 08:52 UTC, reuven12 commented on src/routes/stations.router.ts
> +/* eslint-disable import/no-extraneous-dependencies */
done

2021-08-31 08:52 UTC, closed without merging